const ModalActionTypes = {
    TOGGLE_AVAILABLE_UNITS : 'TOGGLE_AVAILABLE_UNITS',
    TOGGLE_QUARANTINED_UNITS : 'TOGGLE_QUARANTINED_UNITS',
    TOGGLE_UNITS_IN_USE : 'TOGGLE_UNITS_IN_USE',
    TOGGLE_ADD_USER : 'TOGGLE_ADD_USER',
    TOGGLE_ADD_UNIT : 'TOGGLE_ADD_UNIT',
    TOGGLE_ADD_MODEL : 'TOGGLE_ADD_MODEL',
    TOGGLE_ACTIVITY_TRACKING : 'TOGGLE_ACTIVITY_TRACKING',
    TOGGLE_ACTIVITY_REPORT : 'TOGGLE_ACTIVITY_REPORT',
};

export default ModalActionTypes;