const DropDownActionTypes = { 
    REQUEST_ASSET_DROP_DOWN_OPTIONS : 'REQUEST_ASSET_DROP_DOWN_OPTIONS',
    RECEIVE_ASSET_DROP_DOWN_OPTIONS : 'RECEIVE_ASSET_DROP_DOWN_OPTIONS',
    REQUEST_USER_DROP_DOWN_OPTIONS : 'REQUEST_USER_DROP_DOWN_OPTIONS',
    RECEIVE_USER_DROP_DOWN_OPTIONS : 'RECEIVE_USER_DROP_DOWN_OPTIONS',
    REQUEST_MODEL_DROP_DOWN_OPTIONS : 'REQUEST_MODEL_DROP_DOWN_OPTIONS',
    RECEIVE_MODEL_DROP_DOWN_OPTIONS : 'RECEIVE_MODEL_DROP_DOWN_OPTIONS',
};

export default DropDownActionTypes;
