const AssetActionTypes = { 
    REQUEST_SELECTED_ASSET_START : 'REQUEST_SELECTED_ASSET_START',
    REQUEST_SELECTED_ASSET_SUCCESS : 'REQUEST_SELECTED_ASSET_SUCCESS',
    REQUEST_SELECTED_ASSET_FAILURE : 'REQUEST_SELECTED_ASSET_FAILURE',
    CHECK_IN_SELECTED_ASSET_START : 'CHECK_IN_SELECTED_ASSET_START',
    CHECK_IN_SELECTED_ASSET_SUCCESS : 'CHECK_IN_SELECTED_ASSET_SUCCESS',
    CHECK_IN_SELECTED_ASSET_FAILURE : 'CHECK_IN_SELECTED_ASSET_FAILURE',
    CHECK_OUT_SELECTED_ASSET_START : 'CHECK_OUT_SELECTED_ASSET_START',
    CHECK_OUT_SELECTED_ASSET_SUCCESS : 'CHECK_OUT_SELECTED_ASSET_SUCCESS',
    CHECK_OUT_SELECTED_ASSET_FAILURE : 'CHECK_OUT_SELECTED_ASSET_FAILURE',
    QUARANTINE_SELECTED_ASSET_START : 'QUARANTINE_SELECTED_ASSET_START',
    QUARANTINE_SELECTED_ASSET_SUCCESS : 'QUARANTINE_SELECTED_ASSET_SUCCESS',
    QUARANTINE_SELECTED_ASSET_FAILURE : 'QUARANTINE_SELECTED_ASSET_FAILURE',
    REMOVE_SELECTED_ASSET_START :'REMOVE_SELECTED_ASSET_START',
    REMOVE_SELECTED_ASSET_SUCCESS : 'REMOVE_SELECTED_ASSET_SUCCESS',
    REMOVE_SELECTED_ASSET_FAILURE : 'REMOVE_SELECTED_ASSET_FAILURE',  
};

export default AssetActionTypes;