const AssetActionTypes = { 
    REQUEST_SELECTED_ASSET : 'REQUEST_SELECTED_ASSET',
    RECEIVE_SELECTED_ASSET : 'RECEIVE_SELECTED_ASSET',
    CHECK_IN_SELECTED_ASSET_START : 'CHECK_IN_SELECTED_ASSET_START',
    CHECK_IN_SELECTED_ASSET_SUCCESS : 'CHECK_IN_SELECTED_ASSET_SUCCESS',
    CHECK_OUT_SELECTED_ASSET_START : 'CHECK_OUT_SELECTED_ASSET_START',
    CHECK_OUT_SELECTED_ASSET_SUCCESS : 'CHECK_OUT_SELECTED_ASSET_SUCCESS',
    QUARANTINE_SELECTED_ASSET_START : 'QUARANTINE_SELECTED_ASSET_START',
    QUARANTINE_SELECTED_ASSET_SUCCESS : 'QUARANTINE_SELECTED_ASSET_SUCCESS',
};

export default AssetActionTypes;