const SiteMemberActionTypes = {
    HANDLE_MEMBER_SIGN_OUT : 'HANDLE_MEMBER_SIGN_OUT',
    REGISTER_START : 'REGISTER_START',
    REGISTER_SUCCESS : 'REGISTER_SUCCESS',
    REGISTER_FAILURE : 'REGISTER_FAILURE',
    SIGN_IN_START : 'SIGN_IN_START',
    SIGN_IN_SUCCESS : 'SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE : 'SIGN_IN_FAILURE',
};

export default SiteMemberActionTypes;