const UserActionTypes = {
  ADD_NEW_USER_START: 'ADD_NEW_USER_START',
  ADD_NEW_USER_SUCCESS: 'ADD_NEW_USER_SUCCESS',
  ADD_NEW_USER_FAILURE: 'ADD_NEW_USER_FAILURE',
};

export default UserActionTypes;