const DropDownActionTypes = { 
    SET_SELECTED_USER: 'SET_SELECTED_USER',

    FETCH_ASSET_DROP_DOWN_OPTIONS_START: 'FETCH_ASSET_DROP_DOWN_OPTIONS_START',
    FETCH_ASSET_DROP_DOWN_OPTIONS_SUCCESS: 'FETCH_ASSET_DROP_DOWN_OPTIONS_SUCCESS',
    FETCH_ASSET_DROP_DOWN_OPTIONS_FAILURE: 'FETCH_ASSET_DROP_DOWN_OPTIONS_FAILURE',

    FETCH_USER_DROP_DOWN_OPTIONS_START: 'FETCH_USER_DROP_DOWN_OPTIONS_START',
    FETCH_USER_DROP_DOWN_OPTIONS_SUCCESS: 'FETCH_USER_DROP_DOWN_OPTIONS_SUCCESS',
    FETCH_USER_DROP_DOWN_OPTIONS_FAILURE: 'FETCH_USER_DROP_DOWN_OPTIONS_FAILURE',

    FETCH_MODEL_DROP_DOWN_OPTIONS_START: 'FETCH_MODEL_DROP_DOWN_OPTIONS_START',
    FETCH_MODEL_DROP_DOWN_OPTIONS_SUCCESS: 'FETCH_MODEL_DROP_DOWN_OPTIONS_SUCCESS',
    FETCH_MODEL_DROP_DOWN_OPTIONS_FAILURE: 'FETCH_MODEL_DROP_DOWN_OPTIONS_FAILURE',

    SOCKET_UPDATE_ASSET_BREAKDOWN: 'SOCKET_UPDATE_ASSET_BREAKDOWN',
};

export default DropDownActionTypes;
